# Generated by Django 3.1 on 2020-12-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('employeeID', models.CharField(max_length=150)),
                ('extension_num', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cutline', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('line_num', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('line_num',),
            },
        ),
    ]
