# Generated by Django 3.1 on 2021-01-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0002_people_frequent'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='circuleNum',
            field=models.IntegerField(default=0),
        ),
    ]
