# Generated by Django 3.1 on 2021-01-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0004_people_downtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='circuleNum',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
