# Generated by Django 3.1 on 2021-01-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0005_auto_20210107_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='circuleNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='people',
            name='frequent',
            field=models.CharField(choices=[('LTE', 'LTE'), ('WiFi', 'WiFi'), ('GPS', 'GPS')], default='LTE', max_length=10),
        ),
    ]
