# Generated by Django 3.1 on 2021-01-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0006_auto_20210107_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='DownTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
